### ISSUE TITLE
pngquant should have dithering enabled

### ISSUE THREAD

**Issue by kornelski** [voxmedia/image_compression_experiments#1]
Sample images look like they don't have dithering enabled, which makes photo-like look much worse.

**Comment by okor** [comment]
@pornel Oh wow, I think you're correct. This is the command I was using

`cat sourceFile | pngquant --speed=1 --nofs --quality='41-41' - >  destinationFile`

I think I was confused by this line on the pngquant site "Unique adaptive dithering algorithm that adds less noise to images than the standard Floyd-Steinberg" and then running `man pngquant` I saw an option to disable Floyd-Steinberg dithering. So thought that meant that in order to use your improved dithering algorithm I would need to disable the Floyd-Steinberg dithering. Removing that option does indeed make the image appear to be much better. I'll update my code.

**Comment by okor** [comment]
Done https://github.com/voxmedia/image_compression_experiments/commit/c64a8876b04f2f7814f662d720c5f994ebd48d8f
